#!/usr/bin/env python
import json
import optparse
import socket
import sys

from msgbox import *

def abort(msg):
    print >>sys.stderr, msg
    sys.exit(1)

class Options(optparse.OptionParser):
    def __init__(self):
        optparse.OptionParser.__init__(self)
        self.add_option('-r', '--remote', dest='address', default=None)
        self.add_option('-c', '--config-file', dest='config_file', default=None)
        self.add_option('-a', '--args', dest='from_args', action='store_true')
        self.add_option('-f', '--field', dest='fields', action='append',
                        nargs=3, default=[])

def main(args):
    def test(cond, msg):
        if not cond: abort(msg + ', quitting')

    parser = Options()
    (options, args) = parser.parse_args(args)

    from_args = options.from_args or bool(options.fields)
    if not from_args:
        test(not args, "Unexpected positional arguments")

    address = options.address
    if address:
        address = Address.from_str(address)
    else:
        cfg_file = options.config_file or Config.find_config_file_path()
        test(cfg_file and os.path.exists(cfg_file), "No config file found")
        address = Config.load_file(cfg_file).listen_address

    # we figure out what JSON to send...
    if from_args:
        # make a string-string dict from our arguments and explicitly-given
        # fields
        assert len(args) % 2 == 0 # TODO: error message
        jsonobj = dict(zip(args[::2], args[1::2]))
        # add in explicit fields
        type_ctors = {'int': int, 'string': str, 'float': float,
                      'json': json.loads}
        for typ, name, val in options.fields:
            # TODO: handle json.loads failing
            jsonobj[name] = type_ctors[typ](val)
    else:
        # read it from stdin
        jsonobj = json.load(sys.stdin)

    # ... set up the messages we'll send ...
    hello = MessageHelloSender()
    message = MessageGenEvent(jsonobj)
    data = hello.serialize() + message.serialize()

    # ... and send it to the address
    sock = socket.socket(address.socket_address_family(), socket.SOCK_STREAM)
    sock.connect(address.socket_address())

    sent = 0
    while sent < len(data):
        sent += sock.send(buffer(data, sent))
    sock.shutdown(socket.SHUT_RDWR)
    sock.close()
    sys.exit(0)

if __name__ == "__main__": main(sys.argv[1:])
